### ISSUE TITLE
How get the property value of a child component from the parent component?

### ISSUE THREAD

**Issue by jongjunpark** [figma/code-connect#150] opened 2024-09-02 06:01 UTC
We have a component that contains another component within it.
- **parent component**
![image](https://github.com/user-attachments/assets/2fce2c29-34fc-4e41-8c8d-3e314f051cab)

```
parent component (Heading)
ㄴ children component (Number badge)
```

The children component (Number badge) has the following properties and code-connect.
- **children component (Number badge)**
![image](https://github.com/user-attachments/assets/632f4976-2597-4fa1-ac52-b2b30aefe6b2)

So, I want to take the `variant` property value and `figma.textContent("Label")` value of this children component (Number badge), and pass them to the Heading.Badge, which is a part of the parent component Heading. How can I do that?

I try bleow code with `nestedProps` (refer to the following [this](https://github.com/figma/code-connect/issues/11#issuecomment-2203204764)), but get message `Failed to load Code Connect example`
```javascript
figma.connect(
  Heading,
  "https://www.figma.com/design/...",
  {
    props: {
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
        Xlarge: "xLarge",
      }),
      text: figma.textContent("Title"),
      description: figma.boolean("Text", {
        true: figma.textContent("Text"),
        false: undefined,
      }),
      align: figma.enum("Align", {
        Default: undefined,
        Center: "center",
      }),
      badge: figma.nestedProps("Number badge", {
        variant: figma.enum("variant", {
          primary: "primary",
          secondary: "secondary",
          accent: "accent",
          critical: "critical",
          "primary-inverse 🔒": "primary-inverse",
          "secondary-inverse 🔒": "secondary-inverse",
          "accent-inverse 🔒": "accent-inverse",
          "critical-inverse 🔒": "critical-inverse",
        }),
        text: figma.textContent("Label"),
      }),
    },
    example: ({ badge, ...props }) => (
      <Heading {...props}>
        <Heading.Badge type={badge.variant} text={badge.text} />
      </Heading>
    ),
  },
);
```

Please provide:
- Code Connect CLI version: 1.0.6
- Operating system: mac OS 13.5.2

**Comment by slees-figma** [comment] 2024-09-02 15:57
Hey @jongjunpark, I can't see any mistakes in your Code Connect code and this is the way we would recommend to get property values of child components. If you could please raise a [support ticket](https://help.figma.com/hc/en-us/requests/new) and share your file with them we can investigate further.

**Comment by jongjunpark** [comment] 2024-09-03 05:37
> nestedProps

Hi, @slees-figma . I share our file to [support ticket](https://help.figma.com/hc/en-us/requests/new). I hope it gets resolved soon. thanks

**Comment by ptomas-figma** [comment] 2024-09-11 17:25
Hi @jongjunpark, thanks for sharing the file! I looked into it and it seems like the issue is that the badge layer is names `Number badge ` (with a whitespace at the end) and not `Number badge`. 

If you update the ` badge: figma.nestedProps("Number badge"` to ` badge: figma.nestedProps("Number badge "` you should see code snippets for the variants with badge. 

In order to also show code snippets for the variants without badge you should use [Variant restrictions](https://github.com/figma/code-connect/blob/a7fab9331591190cf3b8f449f1f32126d2751cc5/docs/react.md#variant-restrictions) and create different examples for the variants with badge and without.



```
figma.connect(
  Heading,
  "https://www.figma.com/...,
  {
    variant: { Badge: "True" },  // <--- This for variants without badge
    props: {
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
        Xlarge: "xLarge",
      }),
      text: figma.textContent("Title"),
      description: figma.boolean("Text", {
        true: figma.textContent("Text"),
        false: undefined,
      }),
      align: figma.enum("Align", {
        Default: undefined,
        Center: "center",
      }),
      badge: figma.nestedProps("Number badge ", {
        variant: figma.enum("variant", {
          primary: "primary",
          secondary: "secondary",
          accent: "accent",
          critical: "critical",
          "primary-inverse 🔒": "primary-inverse",
          "secondary-inverse 🔒": "secondary-inverse",
          "accent-inverse 🔒": "accent-inverse",
          "critical-inverse 🔒": "critical-inverse",
        }),
        text: figma.textContent("Label"),
      }),
    },
    example: ({ badge, ...props }) => (
      <Heading {...props}>
        <Heading.Badge type={badge.variant} text={badge.text} />
      </Heading>
    ),
  }
);

figma.connect(
  Heading,
  "https://www.figma.com/...,
  {
    variant: { Badge: "False" }, // <--- This for variants with badge
    props: {
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
        Xlarge: "xLarge",
      }),
      text: figma.textContent("Title"),
      description: figma.boolean("Text", {
        true: figma.textContent("Text"),
        false: undefined,
      }),
      align: figma.enum("Align", {
        Default: undefined,
        Center: "center",
      }),
    },
    example: ({ ...props }) => <Heading {...props}></Heading>,
  }
);
```

**Comment by jongjunpark** [comment] 2024-09-12 08:15
hi, @ptomas-figma 
Thank you for the quick response. I hadn’t noticed that there were empty values in the text.
it’s working very well now.
![image](https://github.com/user-attachments/assets/4a5d63c6-ab1e-4672-85e3-58cfddb693e6)

**Comment by ptomas-figma** [comment] 2024-09-12 09:33
Great news! Closing the issue now as resolved. Thanks!

**Closed by ptomas-figma** 2024-09-12 09:33 UTC
Labels: bug
