### ISSUE TITLE
I cannot publish code to figma

### ISSUE THREAD

**Issue by pttchsswk** [figma/code-connect#87] opened 2024-07-03 06:52 UTC
I'm encountering an issue with Figma and npx figma connect (npx figma -V: 1.0.1). Yesterday, I successfully published code-connect using npx figma connect publish --token figd_walksjdlkwa, and it appeared in my Figma. 

However, today, without making any changes, code-connect has disappeared from Figma. I attempted to republish using the same command, but code-connect still doesn't appear in Figma.

 How can I resolve this issue?

**Comment by hedgie001** [comment] 2024-07-03 13:12
Since as of today i was also not able to publish to my figma.
Steps to reproduce:

Chenged directory to my react button and create figma meta file:

`npx figma connect create "https://www.figma.com/design/umyc2pmv9xwMOIVfoRGBvE/test-ui?node-id=1-12&m=dev"`

Changed file to:
```
import { Button } from "./Button"
import figma from "@figma/code-connect"


figma.connect(
  Button,
  "https://www.figma.com/design/nbFMGKm7qZBJHp4z2VWd0i/smoca-ui?node-id=1-8",
  {
    props: {
      label: figma.string("label"),
      type: figma.enum("type", {
        filled: "filled",
        outlined: "outlined",
      }),
      disabled: figma.enum("state",{disabled: true})
    },
      example: (props) => <Button type={props.type} disabled={props.disabled}>{props.label}</Button>,
  },
)
```

Then:
`npx figma connect publish`

My cli says "Successfully uploaded to Figma"

When switching to figma:
- enable Dev Mode
- Click on an instance of said Button component
- Code-Connect window is missing completly

Yesterday everything worked as expected. The bad thing is that i have to present this feature in less than 2 hours :(

**Comment by jyyang0** [comment] 2024-07-03 16:27
Hey folks, thanks for reporting this issue and apologies for the inconvenience. We have identified the issue and are currently working on a fix -- I will post updates here when it is resolved.

**Comment by pttchsswk** [comment] 2024-07-04 01:59
please update if it working again, thanks💖

**Comment by jyyang0** [comment] 2024-07-04 02:31
Hey all, this should be working now -- I'll close this out for now but please reopen it if you're still having trouble seeing code connect

**Closed by jyyang0** 2024-07-04 02:31 UTC

**Comment by pttchsswk** [comment] 2024-07-04 04:23
checked, It's working now
thanks @jyyang0
