### ISSUE TITLE
How to implement Code Connect if in Figma have a toggle

### ISSUE THREAD

**Issue by pttchsswk** [figma/code-connect#70] opened 2024-06-24 07:05 UTC
in Figma I have a toggle "is Unavailable" (can be "Yes", "No")
<img width="201" alt="Screenshot 2567-06-24 at 13 59 04" src="https://github.com/figma/code-connect/assets/158119549/8594aabf-8fdd-469e-8c04-5833700f64c5">

in component.figma.tsx 
```figma.connect(
  AvatarCTA,
  "https://www.figma.com/design/213213213wasfasdasdsad/asdsadasdsad-%26-Organisms?node-id=13-sssad&m=dev",
  {
    props: {
      label: figma.string("Label"),
      showDescription: figma.boolean("show Description"),
      isUnavailable: figma.boolean("is Unavailable"),
    },
    example: (props) => <AvatarCTA isUnAvailable={props.isUnavailable} />,
  }
);```

I want to show code in connect at figma like

`<AvatarCTA isUnAvailable={true} /> // when isUnavailable toggle is Yes`
`<AvatarCTA isUnAvailable={false} /> // when isUnavailable toggle is No`

how should I implement?

very urgent please help

**Comment by ptomas-figma** [comment] 2024-06-24 23:52
Hi, this seems like code that should work. What issue are you seeing when publishing?

**Comment by pttchsswk** [comment] 2024-06-25 03:14
Hi @ptomas-figma thanks for your support

this my code
![Screenshot 2567-06-25 at 10 10 34](https://github.com/figma/code-connect/assets/158119549/11fc4b72-f145-4c77-99f2-738f63be6341)

and this is result 
- showIcon props is not visible
![Screenshot 2567-06-25 at 10 09 38](https://github.com/figma/code-connect/assets/158119549/5f6ab01a-a4ec-4191-b017-99099a51add0)

how should I implement code to show showIcon like red text in second image?

**Comment by karlpetersson** [comment] 2024-06-25 17:26
Hey again - I was able to reproduce this issue now. A possible workaround for this is to rename the values of `show Icon` to "True" or "False" (case sensitive) in Figma - this seems to be an issue if lowercase values are used like "yes" or "true". Let me know if that works for you. In any case, we'll aim to have this fixed in the next release

**Comment by pttchsswk** [comment] 2024-06-28 02:02
Sorry for late reply, I will update you by today

**Closed** 2024-09-04 16:22 UTC
Labels: fixed in next release
